### PR TITLE
added a linter check with github actions

### LINKED ISSUE #36: Add a linter check with github actions
- Add a linter to the project. Can it be black?
- Add a respective GitHub action for lining analysis.

### PR DESCRIPTION
**Pull request by slayer321**
fix #36 
I have tested it on my side. and I didn't find any error.
If anything needs to be updated let me know.

### CODE REVIEW

**Comment by Pradhvan** [comment]
@slayer321 can you squash all four commits into one ? 

Also it would great if you could ammend your commit and format it in a particular standard.

**Comment by slayer321** [comment]
@Pradhvan  is it ok if I just close this PR and open a new PR?

**Comment by Pradhvan** [comment]
@slayer321 let's not do that. Let's try to update the existing PR. 

Do you need help with anything?

**Comment by slayer321** [comment]
I think that I just messed it up 😅 . I change the branch name from `slayer321-patch-1-1` to `slayer321-patch-1` and now the PR is showing close.


> @slayer321 let's not do that. Let's try to update the existing PR.
> 
> Do you need help with anything?

Yes, all the changes that I did in the .workflow dir were on the GitHub website and I didn't use `git bash ` for this. So now I don't have that branch on my git bash.
I checked how to squash all my four commits to one, but I need this branch and I don't have this branch on my git bash so how can it be done?

**Comment by Pradhvan** [comment]
@slayer321 great! you did found a way to restore a branch.

**Pull request closed without merging**
