### PR TITLE
Fix rest-auth registration

### LINKED ISSUE #39: Error 500 when registering a new user
### Environment
- Operating System: MacOS
- Browser: Chrome

### Description of the bug 
Error 500 when registering a new user

### Expected behavior ?
A new user registered, created in the database

### How to reproduce the the bug ?
Go to https://demo.scanapi.dev/api/v1/rest-auth/registration/ and try to register a new user

image

### PR DESCRIPTION
**Pull request by camilamaia**
Closes #39

### CODE REVIEW

**Comment by Pradhvan** [comment]
@camilamaia did you directly add the user in the DB to create a new user? If yes, can you please list the steps for it. 

I usually create a super user using the built-in commands since we don't have any mechanism for adding new users to the API.

**Comment by camilamaia** [comment]
@Pradhvan the superuser I've created using the manage.py command, as you said:

```bash
python manage.py createsuperuser
```

But people will not need it, since they can use the endpoint now:

```
/api/v1/rest-auth/registration
```

Maybe only for running locally, if they want to manage the users directly...

**Review by Pradhvan — APPROVED** [review]
🦸🏾‍♀️  Good to go!

**Comment by camilamaia** [comment]
@Pradhvan I see in a different way. This is a REST endpoint, so I believe its obligation is only to register the user. It is not an UI feature, like the login and logout button in the menu bar

image

These buttons, I agree with you, they should redirect to the previous page/ or home, as you prefer.

What do you think? 

(I am merging the PR, but let's keep discussing it here. If we think it is missing the redirect, we can add a new issue)

**Pull request merged**
